Repository DuncanMoyo/AirBnB_clone, pull requests merged in 2023-08, with the labels that each got.

#13 Added authors file
  AUTHORS
Labels: documentation

#15 Task 3 - BaseModel
  .gitignore
  models/__pycache__/base_model.cpython-38.pyc
  models/base_model.py
Labels: good first issue

#16 Task 4 - already addressed, added alx test file to gitignore
  .gitignore
  models/__pycache__/base_model.cpython-38.pyc
Labels: enhancement

#17 Task 5 - Store first object
  .gitignore
  file.json
  models/__init__.py
  models/__pycache__/__init__.cpython-38.pyc
  models/__pycache__/base_model.cpython-38.pyc
  models/base_model.py
  models/engine/__init__.py
  models/engine/__pycache__/__init__.cpython-38.pyc
  models/engine/__pycache__/file_storage.cpython-38.pyc
  models/engine/file_storage.py
Labels: enhancement

#19 9 first user
  .gitignore
  console.py
  file.json
  models/__pycache__/__init__.cpython-38.pyc
  models/__pycache__/base_model.cpython-38.pyc
  models/__pycache__/user.cpython-38.pyc
  models/engine/__pycache__/__init__.cpython-38.pyc
  models/engine/__pycache__/file_storage.cpython-38.pyc
  models/engine/file_storage.py
  models/user.py
  test_save_reload_user.py
Labels: enhancement

#23 Updated README and console file
  README.md
  console.py
  file.json
  models/__pycache__/__init__.cpython-38.pyc
  models/__pycache__/base_model.cpython-38.pyc
  models/__pycache__/user.cpython-38.pyc
  models/engine/__pycache__/__init__.cpython-38.pyc
  models/engine/__pycache__/file_storage.cpython-38.pyc
Labels: documentation

#32 25 advanced tasks
  console.py
  file.json
  models/__pycache__/__init__.cpython-38.pyc
  models/__pycache__/base_model.cpython-38.pyc
  models/__pycache__/user.cpython-38.pyc
  models/engine/__pycache__/__init__.cpython-38.pyc
  models/engine/__pycache__/file_storage.cpython-38.pyc
Labels: enhancement

#33 26 add unittests for the console
  .gitignore
  console.py
  file.json
  models/engine/__pycache__/file_storage.cpython-38.pyc
  tests/test_console.py
  tests/test_models/test_base_model.py
Labels: documentation

#38 Unittest for file storage
  tests/test_models/test_engine/__init.py__
  tests/test_models/test_engine/test_file_storage.py
Labels: enhancement
